### ISSUE TITLE
AttributeError: 'long' object has no attribute 'swagger_types'

### ISSUE THREAD

**Issue by moyeen52** [artikcloud/artikcloud-python#1]
For self.messages_api.get_normalized_messages(start_date=1464924663788,end_date=1464928263788)  this style calling I'm getting the following error  
Module artikcloud.apis.messages_api, line 508, in get_normalized_messages
  Module artikcloud.api_client, line 321, in call_api
  Module artikcloud.api_client, line 126, in __call_api
  Module artikcloud.api_client, line 218, in sanitize_for_serialization
  Module artikcloud.api_client, line 218, in <dictcomp>
  Module artikcloud.api_client, line 215, in sanitize_for_serialization
AttributeError: 'long' object has no attribute 'swagger_types'

can see sys.maxint size exceeds.

**Comment by yujingwu** [comment]
@maneeshsahu  Please take a look. Thank you!

**Comment by maneeshsahu** [comment]
Fixed in 2.0.3.

`pip install artikcloud`
