### ISSUE TITLE
Optional named parameters of value None

### ISSUE THREAD

**Issue by jonathanpaek** [artikcloud/artikcloud-python#5]
``` python
api_response = api_instance.get_normalized_messages(uid=uid, sdid=sdid, mid=mid, field_presence=field_presence, filter=filter, offset=offset, count=count, start_date=start_date, end_date=end_date, order=order)
```

may affect the other SDKs as well.

looks like swagger is is already taking a look as it doesn't yet support optional params for all languages yet
https://github.com/swagger-api/swagger-codegen/issues/3665

**Comment by yujingwu** [comment]
@jonathanpaek 

If a parameter (e.g. uid) is an optional request parameter of REST call [Get normalized messages](https://developer.artik.cloud/documentation/api-reference/rest-api.html#get-normalized-messages), you can pass it as None (Python's null equivalent) when using the corresponding python sdk method (mentioned above), .

For example,
api_response = api_instance.get_normalized_messages(None, sdid, None, None, None, None, 2, start_date, end_date, None);

Does this solve your problem?

**Comment by jonathanpaek** [comment]
No - Using None in that fashion results in a compilation TypeError.

However, I tried setting None specifically with named arguments in the following fashion:

``` python
api_instance.get_normalized_messages(uid=None, sdid=None, ..., count=None, order=None)
```

This would still results in type error, for example, since None cannot convert to an int type for certain types, for example.  However, some luck -  the workaround would be to not include the parameter at all within the method call.   For example: 

``` python
api_instance.get_normalized_messages()
```

After more investigation, the problem appears to be 2 things:  1) type checking 2) and when None is set as a named argument, the request is not omitting the request parameter.
