### ISSUE TITLE
permissions error?

### ISSUE THREAD

**Issue by terrenjpeterson** [artikcloud/artikcloud-python#8]
In setting this up, i'm getting a 403 error using the DeviceTypesAPI.  It appears that the device_type might be null - any insight in how to troubleshoot?  the message is "You do not have the right permission: 'device_type' ['']"

**Comment by jonathanpaek** [comment]
@terrenjpeterson  the associated **access token**  should have access to the _device type_ (either created by you, or published/public).   please try using a user access token — simply retrieve yours with [Get Current User API](https://developer.artik.cloud/api-console/) call while you are logged in.

**Comment by terrenjpeterson** [comment]
Thanks @jonathanpaek - that was it!
